spring:
  application:
    name: client-example
  cloud:
    consul:
      host: 192.168.205.129
      port: 8500
      discovery:
        enabled: true
        register: false
        deregister: true
        service-name: client-example

server:
  port: 9001

management:
  endpoint:
    # 启用pause端点
    pause:
      enabled: true
    # 启用restart端点，之所以要启用restart端点，是因为pause端点的启用依赖restart端点的启用
    restart:
      enabled: true
  endpoints:
    web:
      exposure:
        include: pause,restart

nexus:
  registry:
    protocol: consul
  cluster:
    load-balance: random
  max-connection: 20


---
spring:
  config:
    activate:
      on-profile: 9001

server:
  port: 9001

nexus:
  registry:
    protocol: consul
  cluster:
    load-balance: random


---
spring:
  config:
    activate:
      on-profile: 9002

server:
  port: 9002

nexus:
  registry:
    protocol: consul
  cluster:
    load-balance: random
