spring:
  application:
    name: server-example

nexus:
  port: 1234
  registry:
    protocol: redis
    port: 6379
    ip: 127.0.0.1
  rpc-role: server


---
spring:
  config:
    activate:
      on-profile: dev1

nexus:
  port: 1234
  registry:
    protocol: redis
    port: 6379
    ip: 127.0.0.1
  rpc-role: server


---
spring:
  config:
    activate:
      on-profile: dev2

nexus:
  port: 1235
  registry:
    protocol: redis
    port: 6379
    ip: 127.0.0.1
  rpc-role: server