spring:
  application:
    name: server-example
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true
        deregister: true
        health-check-critical-timeout: 10s
        service-name: server-example
        heartbeat:
          enabled: true


nexus:
  service-name: server-example
  port: 1234
  registry:
    protocol: consul

server:
  port: 1478

---
spring:
  config:
    activate:
      on-profile: dev1

server:
  port: 1478

nexus:
  service-name: server-example
  port: 1234
  registry:
    protocol: consul


---
spring:
  config:
    activate:
      on-profile: dev2
server:
  port: 1479
nexus:
  service-name: server-example
  port: 1235
  registry:
    protocol: consul